# Site settings
author: Kevin Boston
title: A Program of Reflection
header-img: img/home-bg.png
email: kbos22@gmail.com
copyright_name: Kevin Boston
description: > # this means to ignore newlines until "baseurl:"
  Musings on computer science and coding
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  KevinBoston

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
